In [18]:
import numpy as np
import math
from IPython.display import display, Math, Latex, Markdown

np.set_printoptions(suppress=True, linewidth=95) # Ajuste para la presentación en pantalla con print()


singular = False

def crea_matriz():
    """
    Crea la matriz ampliada del sistema de ecuaciones a partir de la entrada
    del usuario y solicita del mismo el ajuste de cifras significativas
    """
    A =[]
    # Número de filas, es también el de incógnitas
    filas = int(input('Número de incógnitas: '))
    # Columnas de la ampliada = número de filas + 1
    columnas = filas 
    # Ajuste de cifras significativas
    #significativas = int(input('Cifras significativas requeridas (0 para ignorar): ') or '0')
    # Entrada de las ecuaciones
    print('Introduzca cada ecuación seguida de "Enter" (ejemplo: 2x+y+3z=4 => 2 1 3 4): ')
    for i in range(filas):
        nfila = list(map(float, input().rstrip().split()))
        while len(nfila) != columnas :
            print('Entrada inválida, ha introducido {} coeficientes y ha de ser igual a {}. Vuelva a intentarlo: '.format(len(nfila), columnas))
            nfila = list(map(ajusta_entrada, input().rstrip().split()))
        A.append(nfila)
    display(Markdown('__Matriz A:__ '))
    muestra_matriz(A)
    return (A)

def muestra_matriz(m):
    """
    Muestra una matriz fila a filalongitud
    param m: matriz que se desea mostrar
    """
    for linea in m:
        display(linea)

def lu(A):
    """
    Función que realiza la factorización LU de una matriz por
    el método Doolittle que requiere que la diagonal principal de L
    esté formada toda por 1.
    Devuelve las latrices triangulares L y U
    
    param A: List; matriz a descomponer
    
    """
    n = len(A)
    cols= len(A[0])
    suma0 = 0
    suma1 = 0
    suma2 = 0
    suma3 = 0
    suma4 = 0
    singular = None
    
    global num_sumas # Recoje el número total de sumas y/o diferencias
    global num_productos # Recoje el número total de productos y/o cocientes
    
    num_sumas = 0
    num_productos = 0


    l = np.zeros((len(A), len(A))) # Se inicializan las matrices L y U
    u = np.zeros((len(A), len(A))) #
    u[0][0] = A[0][0]
    l[0][0] = A[0][0]
    
    for i in range(n):
        l[i][i] = 1.
    
    for j in range(0, n):
        u[0][j] = A[0][j] # Primera fila de U
    for j in range (1, n):
        l[j][0] = A[j][0]/u[0][0] # Primera columna de L
        num_productos +=1
        
    for i in range(1, n-1):
        suma1 = 0
        for k in range(0, i):
            suma1 += l[i][k]*u[k][i]
            num_sumas += 1
            num_productos += 1
        u[i][i] = A[i][i] - suma1
        num_sumas += 1
        if l[i][i] * u[i][i] == 0:
            return('Factorización imposible')
        for j in range(i+1, n):
            suma2 = 0
            suma3 = 0
            for k in range(0, i):
                suma2 += l[i][k]*u[k][j]
                num_sumas += 1
                num_productos += 1
                suma3 += l[j][k]*u[k][i]
                num_sumas += 1
                num_productos += 1
                #print(suma2, ' - ', suma3)
            u[i][j] = (1/l[i][i])*(A[i][j]-suma2)  # i-ésima fila de U
            l[j][i] = (1/u[i][i])*(A[j][i]-suma3) # i-ésima columna de L
            num_sumas += 2
            num_productos += 4
            
    for k in range(0, n):
        #suma4 = 0
        suma4 += l[n-1][k]*u[k][n-1]
        num_sumas += 1
        num_productos += 1
        #print('suma4 :', suma4, ', k :', k)
    u[n-1][n-1] = A[n-1][n-1] - suma4
    num_sumas += 1
    if (l[n-1][n-1]*u[n-1][n-1] == 0):
        singular = True
    return(l, u)

matriz =[[1.0, 1.0, 0.0, 3.0],
         [2.0, 1.0, -1.0, 1.0],
         [3.0, -1.0, -1.0, 2.0],
         [-1.0, 2.0, 3.0, -1.0]]
matriz2 = [[1.0, -1.0, 0.0, 0.0, -1.0, 0.0, 0.0],
[1.0, 0.0, -1.0, 0.0, 0.0, 0.0, -1.0],
[0.0, 1.0, 0.0, -1.0, 0.0, 1.0, 0.0],
[1.0, 0.0, 0.0, 0.0, 5.0, 0.0, 5.0],
[0.0, -3.0, 0.0, 0.0, 5.0, 5.0, 0.0],
[0.0, 0.0, 0.0, 10.0, 0.0, 5.0, 0.0],
[0.0, 0.0, -10.0, 0.0, 0.0, 0.0, 5.0]]

# Matriz apartado c) PEC 2
matrizB = [[10.0, 5.0, 0.0, 0.0, 0.0, 0.0, 0.0],
           [-1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0],
           [0.0, 5.0, -3.0, 5.0, 0.0, 0.0, 0.0],
           [0.0, 0.0, -1.0, -1.0, 1.0, 0.0, 0.0],
           [0.0, 0.0, 0.0, 5.0, 1.0, 5.0, 0.0],
           [0.0, 0.0, 0.0, 0.0, 1.0, -1.0, -1.0],
           [0.0, 0.0, 0.0, 0.0, 0.0, 5.0, -10.0]
            ]

#miL, miU = lu(crea_matriz())
miL, miU = lu(matrizB)
if (singular):
    display(Markdown('**Atención:** la matriz A es **singular**'))

display(Markdown('**Matriz L:**'))
print(np.asarray(miL))
display(Markdown('**Matriz U:**'))
print(np.asarray(miU))

display(Markdown(("<br>__Número de sumas/diferencias: {}.<br>Número de productos/cocientes: {}.__".format(num_productos, num_sumas))))
display(Markdown(("<br>__Número total de operaciones: {}.__".format(num_productos + num_sumas))))

**Matriz L:**

[[ 1.          0.          0.          0.          0.          0.          0.        ]
 [-0.1         1.          0.          0.          0.          0.          0.        ]
 [ 0.          3.33333333  1.          0.          0.          0.          0.        ]
 [ 0.          0.          0.15789474  1.          0.          0.          0.        ]
 [ 0.          0.         -0.         -2.79411765  1.          0.          0.        ]
 [ 0.          0.         -0.         -0.          0.26356589  1.          0.        ]
 [ 0.          0.         -0.         -0.          0.         -2.15719064  1.        ]]


**Matriz U:**

[[ 10.           5.           0.           0.           0.           0.           0.        ]
 [  0.           1.5          1.           0.           0.           0.           0.        ]
 [  0.           0.          -6.33333333   5.           0.           0.           0.        ]
 [  0.           0.           0.          -1.78947368   1.           0.           0.        ]
 [  0.           0.           0.           0.           3.79411765   5.           0.        ]
 [  0.           0.           0.           0.           0.          -2.31782946  -1.        ]
 [  0.           0.           0.           0.           0.           0.         -12.15719064]]


<br>__Número de sumas/diferencias: 158.<br>Número de productos/cocientes: 128.__

<br>__Número total de operaciones: 286.__

In [16]:
tind = np.array([10, 0, 10, 0, 5, 0, 10])

yarray = np.linalg.solve(miL, tind)
print(yarray)
xarray = np.linalg.solve(miU, yarray)
print('======== resultado para x ========')
print(xarray)


[10.          1.          6.66666667 -1.05263158  2.05882353 -0.54263566  8.82943144]
======== resultado para x ========
[ 0.44429161  1.11141678 -0.66712517  0.48830812 -0.17881706  0.5474553  -0.72627235]
