In [7]:
import numpy as np
from IPython.display import Markdown

np.set_printoptions(suppress=True, linewidth=95) # Ajuste para la presentación en pantalla con print()

def crea_matriz():
    """
    Crea la matriz  del sistema de ecuaciones a partir de la entrada
    del usuario y solicita del mismo el ajuste de cifras significativas
    """
    A =[]
    # Número de filas, es también el de incógnitas
    filas = int(input('Número de incógnitas: '))
    columnas = filas 

    # Entrada de las filas de la matriz
    print('Introduzca cada fila seguida de "Enter" (ejemplo: (2 1 3 4) => 2 1 3 4): ')
    for i in range(filas):
        nfila = list(map(float, input().rstrip().split()))
        while len(nfila) != columnas :
            print('Entrada inválida, ha introducido {} elementos y han de ser igual a {}. Vuelva a intentarlo: '.format(len(nfila), columnas))
            nfila = list(map(float, input().rstrip().split()))
        A.append(nfila)
    display(Markdown('__Matriz A:__ '))
    muestra_matriz(A)
    return (A)

def muestra_matriz(m):
    """
    Muestra una matriz fila a fila
    param m: matriz que se desea mostrar
    """
    for linea in m:
        display(linea)

def crout(A):
    """
    Implementación del método de Crout para la factorización de una matriz A.
    Devuelve la matriz triangular inferior, L, y la matriz triangular
    superior, U, de dicha matriz A, tal que L*U=A
    Este método se caracteriza porque requiere que todos los elementos de la 
    diagonal principal de la matriz U sean 1.
    
    param A: matriz que se desea factorizar.
    
    """
    n = len(A)
    cols= len(A[0])

    l = np.zeros((len(A), len(A))) # Se inicializan las matrices L y U
    u = np.zeros((len(A), len(A))) #
    
    global num_sumas # Recoje el número total de sumas y/o diferencias
    global num_productos # Recoje el número total de productos y/o cocientes
    
    num_sumas = 0
    num_productos = 0
    
    for k in range(0, n):
        u[k, k] = 1 

        for j in range(k, n):
            sum0 = 0
            for s in range(0, j):
                sum0 +=  l[j, s ]* u[s, k]
                if l[j, s]!=0 and u[s, k]!=0:
                    num_sumas += 1
                    num_productos +=1
            l[j, k] = A[j, k] - sum0 
            if A[j, k]!=0 and sum0!=0:
                num_sumas += 1

        for j in range(k+1, n):
            sum1 = 0
            for s in range(0, k):
                sum1 += l[k, s] * u[s, j]
                if l[k, s]!=0 and u[s, j]!=0:
                    num_sumas += 1
                    num_productos +=1
            
            u[k, j] = (A[k, j] - sum1) / l[k, k]
            if A[k, j]!=0 and sum1!=0:
                num_sumas += 1
            if A[k, j]!=0 or sum1!=0:
                num_productos +=1

    print('MATRIZ L ====================================')
    print(l)
    print('MATRIZ U ====================================')
    print(u)
    return l, u

#A = np.array([[60.0, 30.0, 20.0], [30.0, 20.0, 15.0], [20.0, 15.0, 12.0]])

#####################################################################
# Por comodidad se han escrito aquí las matrices de los             #
# apartados correspondientes del enunciado.                         #
# Si se desea utilizar con cualquier otra matriz empleando          #
# la entrada de usuario implementada, la llamada a la función       #
# ha de hacerse de la siguiente forma:                              #
#                                                                   #
#    matriz_resultadoL, matriz_resultadoU = crout(crea_matriz())    #
#                                                                   #
#####################################################################

# Matriz apartado b) PEC 2
matriz2 = [[1.0, -1.0, 0.0, 0.0, -1.0, 0.0, 0.0],
    [1.0, 0.0, -1.0, 0.0, 0.0, 0.0, -1.0],
    [0.0, 1.0, 0.0, -1.0, 0.0, 1.0, 0.0],
    [1.0, 0.0, 0.0, 0.0, 5.0, 0.0, 5.0],
    [0.0, -3.0, 0.0, 0.0, 5.0, 5.0, 0.0],
    [0.0, 0.0, -10.0, 0.0, 0.0, 0.0, 5.0],
    [0.0, 0.0, 0.0, 10.0, 0.0, 5.0, 0.0]
    ]
# Matriz apartado c) PEC 2
matrizB = [[10.0, 5.0, 0.0, 0.0, 0.0, 0.0, 0.0],
           [-1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0],
           [0.0, 5.0, -3.0, 5.0, 0.0, 0.0, 0.0],
           [0.0, 0.0, -1.0, -1.0, 1.0, 0.0, 0.0],
           [0.0, 0.0, 0.0, 5.0, 1.0, 5.0, 0.0],
           [0.0, 0.0, 0.0, 0.0, 1.0, -1.0, -1.0],
           [0.0, 0.0, 0.0, 0.0, 0.0, 5.0, -10.0]
            ]

#display(Markdown(('__=================== MATRIZ A ===================__')))
#A = np.asarray(matriz2)
#ml, mu = crout(A)

display(Markdown(('__=================== MATRIZ B ===================__')))
B = np.asarray(matrizB)
mbl, mbu = crout (B)

display(Markdown(("<br>__Número de sumas/diferencias: {}.<br>Número de productos/cocientes: {}.__".format(num_productos, num_sumas))))
display(Markdown(("<br>__Número total de operaciones: {}.__".format(num_productos + num_sumas))))

__=================== MATRIZ B ===================__

MATRIZ L ====================================
[[ 10.           0.           0.           0.           0.           0.           0.        ]
 [ -1.           1.5          0.           0.           0.           0.           0.        ]
 [  0.           5.          -6.33333333   0.           0.           0.           0.        ]
 [  0.           0.          -1.          -1.78947368   0.           0.           0.        ]
 [  0.           0.           0.           5.           3.79411765   0.           0.        ]
 [  0.           0.           0.           0.           1.          -2.31782946   0.        ]
 [  0.           0.           0.           0.           0.           5.         -12.15719064]]
MATRIZ U ====================================
[[ 1.          0.5         0.          0.          0.          0.          0.        ]
 [ 0.          1.          0.66666667  0.          0.          0.          0.        ]
 [ 0.          0.          1.         -0.78947368 -0.         -0.         -

<br>__Número de sumas/diferencias: 12.<br>Número de productos/cocientes: 12.__

<br>__Número total de operaciones: 24.__

In [18]:
tind = np.array([10, 0, 10, 0, 5, 0, 10])

yarray = np.linalg.solve(mbl, tind)
print(yarray)
xarray = np.linalg.solve(mbu, yarray)
print('======== resultado para x ========')
print(xarray)


[ 1.          0.66666667 -1.05263158  0.58823529  0.54263566  0.23411371 -0.72627235]
======== resultado para x ========
[ 0.44429161  1.11141678 -0.66712517  0.48830812 -0.17881706  0.5474553  -0.72627235]


In [43]:
from fractions import Fraction
print(Fraction(28.04347826).limit_denominator())
print(Fraction(-10.86956522).limit_denominator())

645/23
-250/23


In [41]:
tind = np.array([10, 0, 10, 0, 5, 0, 10])


yarray = np.linalg.solve(ml, tind)
print(yarray)
xarray = np.linalg.solve(mu, yarray)
print('======== resultado para x ========')
print(xarray)

[ 10.         -10.          20.         -20.          -1.08695652  -5.           3.92022008]
======== resultado para x ========
[ 5.88033012  0.97661623  1.96011004 -2.34112792 -5.09628611  6.68225585  3.92022008]
